image: node:10.14.1

stages:
  - lint
  - test
  - build
  
cache:
  paths:
    - node_modules
    - ${PKG_CACHE_PATH}

variables:
  PKG_CACHE_PATH: ./pkg-cache
  
lint:
  tags:
    - docker
    - codecove
  stage: lint
  script:
    - npm install
    - npm run lint
  except:
    - tags
  
test:
  tags:
    - docker
    - codecove
  stage: test
  script:
    - npm install
    - npm run test:ci
  except:
    - tags

build_latest:
  tags:
    - docker
    - codecove
  stage: build
  script:
    # Install packages
    - npm install
    - npm install --no-save pkg
    # Compile ts into js
    - ./node_modules/.bin/tsc
    - cp package.json dist
    # Compile package for various systems
    - ./node_modules/.bin/pkg -t node10-linux-x64,node10-macos-x64,node10-win-x64 dist/index.js --output gittt-${CI_COMMIT_SHORT_SHA}
  artifacts:
    name: "gittt-${CI_COMMIT_SHORT_SHA}"
    # TODO use never https://gitlab.com/gitlab-org/gitlab-ce/issues/47878
    expire_in: "420 yrs"
    paths:
      - gittt-*
  only:
    - master

build_tag:
  tags:
    - docker
    - codecove
  stage: build
  script:
    # Install packages
    - npm install
    - npm install --no-save pkg
    # Compile ts into js
    - ./node_modules/.bin/tsc
    - cp package.json dist
    # Compile package for various systems
    - ./node_modules/.bin/pkg -t node10-linux-x64,node10-macos-x64,node10-win-x64 dist/index.js --output gittt-${CI_COMMIT_TAG}
  artifacts:
    name: "gittt-${CI_COMMIT_TAG}"
    # TODO use never https://gitlab.com/gitlab-org/gitlab-ce/issues/47878
    expire_in: "420 yrs"
    paths:
      - gittt-*
  only:
    - tags