image: node:10.14.1

stages:
  - lint
  - test
  - build
  
cache:
  paths:
    - node_modules
  
lint:
  tags:
    - docker
    - codecove
  stage: lint
  script:
    - npm install
    - npm run lint
  
test:
  tags:
    - docker
    - codecove
  stage: test
  script:
    - npm install
    - npm run test:ci
  except:
    - tags

build:
  tags:
    - docker
    - codecove
  stage: build
  script:
    # Install packages
    - npm install -g pkg
    - npm install
    # Compile ts into js
    - ./node_modules/.bin/tsc
    - cp package.json dist
    # Compile package for various systems
    - pkg -t node10-linux-x64,node10-macos-x64,node10-win-x64 dist/index.js --output gittt-${CI_COMMIT_SHORT_SHA}
  artifacts:
    paths:
      - gittt-*
  variables:
    PKG_CACHE_PATH: ./pkg-cache
  cache:
    paths:
      - ${PKG_CACHE_PATH}
  only:
    - master
    - GITTT-51-Release-management-for-cli