image: node:10.14.1

stages:
  - test
  - build
  
cache:
  paths:
    - node_modules
  
test:
  tags:
    - docker
    - codecove
  stage: test
  script:
    - npm install
    - npm run test:ci
  except:
    - tags

build:
  tags:
    - docker
    - codecove
  stage: build
  script:
    # Install packages
    - npm install -g pkg
    - npm install
    # Compile ts into js
    - ./node_modules/.bin/tsc
    - cp package.json dist
    # Compile package for various systems
    - pkg -t node10-linux-x64,node10-macos-x64 dist/index.js --out-path dist
    # Cleanup
    - rm -rf dist/index.js
    - rm -rf dist/package.json
  artifacts:
    paths:
      - "dist"
  only:
    - master