jobs:
  include:
  - stage: debug_build
    branches:
      only:
        - 90-Cleanup-production-binary
    language: node_js
    cache: npm
    node_js:
      - 12.13.1
    script:
      - npm i -g pkg
      # Install packages
      - npm install --production
      # Compile ts into js
      - npm run build:prod
      # File is used by app.ts
      - cp package.json dist
      # Remove tests from dist
      - rm -rf dist/test
      # Compile package for various systems
      - ./node_modules/.bin/pkg -t node12-linux-x64,node12-macos-x64,node12-win-x64 dist/index.js --output gittt-debug
      - ls -ahl 